# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  Arm_Arm_Metal_to_Forearm_Forearm_Metal:
    has_velocity_limits: true
    max_velocity: 25.1327412287
    has_acceleration_limits: false
    max_acceleration: 0
  End_Effector_MIP_Gripper_Interface_to_End_Effector_MIP_Tooth_Left:
    has_velocity_limits: true
    max_velocity: 10000
    has_acceleration_limits: false
    max_acceleration: 0
  End_Effector_MIP_Gripper_Interface_to_End_Effector_MIP_Tooth_Right:
    has_velocity_limits: true
    max_velocity: 10000
    has_acceleration_limits: false
    max_acceleration: 0
  Forearm_Forearm_Metal_to_End_Effector_MIP_Gripper_Interface:
    has_velocity_limits: true
    max_velocity: 25.1327412287
    has_acceleration_limits: false
    max_acceleration: 0
  Shoulder_to_Arm_Arm_Metal:
    has_velocity_limits: true
    max_velocity: 25.1327412287
    has_acceleration_limits: false
    max_acceleration: 0
  Tower_Base_to_Shoulder:
    has_velocity_limits: true
    max_velocity: 10000
    has_acceleration_limits: false
    max_acceleration: 0