# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: mip_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - Tower_Base_to_Shoulder
    - Shoulder_to_Arm_Arm_Metal
    - Arm_Arm_Metal_to_Forearm_Forearm_Metal
    - Forearm_Forearm_Metal_to_End_Effector_MIP_Gripper_Interface
    - End_Effector_MIP_Gripper_Interface_to_End_Effector_MIP_Tooth_Left
    - End_Effector_MIP_Gripper_Interface_to_End_Effector_MIP_Tooth_Right
  sim_control_mode: 1  # 0: position, 1: velocity

mip_junior_300:
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  mip_arm_controller:
    type: position_controllers/JointTrajectoryController
    publish_rate: 50
    joints:
      - Tower_Base_to_Shoulder
      - Shoulder_to_Arm_Arm_Metal
      - Arm_Arm_Metal_to_Forearm_Forearm_Metal
      - Forearm_Forearm_Metal_to_End_Effector_MIP_Gripper_Interface
    constraints:
      goal_time: 0.6
      Tower_Base_to_Shoulder:
        goal: 0.001 #tolerance in m
      Shoulder_to_Arm_Arm_Metal:
        goal: 0.01 #tolerance in radian
      Arm_Arm_Metal_to_Forearm_Forearm_Metal:
        goal: 0.01
      Forearm_Forearm_Metal_to_End_Effector_MIP_Gripper_Interface:
        goal: 0.01
    gains:
      Tower_Base_to_Shoulder:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      Shoulder_to_Arm_Arm_Metal:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      Arm_Arm_Metal_to_Forearm_Forearm_Metal:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      Forearm_Forearm_Metal_to_End_Effector_MIP_Gripper_Interface:
        p: 100
        d: 1
        i: 1
        i_clamp: 1

  mip_gripper_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
    joints:
      - End_Effector_MIP_Gripper_Interface_to_End_Effector_MIP_Tooth_Left
      - End_Effector_MIP_Gripper_Interface_to_End_Effector_MIP_Tooth_Right
    constraints:
      goal_time: 0.6
      End_Effector_MIP_Gripper_Interface_to_End_Effector_MIP_Tooth_Left:
        goal: 0.001 #tolerance in m
      End_Effector_MIP_Gripper_Interface_to_End_Effector_MIP_Tooth_Right:
        goal: 0.01 #tolerance in radian
    gains:
      End_Effector_MIP_Gripper_Interface_to_End_Effector_MIP_Tooth_Left:
        p: 60
        i: 0
        d: 10
        i_clamp: 1
      End_Effector_MIP_Gripper_Interface_to_End_Effector_MIP_Tooth_Right:
        p: 60
        i: 0
        d: 10
        i_clamp: 1

controller_list:
  - name: mip_junior_300/mip_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - Tower_Base_to_Shoulder
      - Shoulder_to_Arm_Arm_Metal
      - Arm_Arm_Metal_to_Forearm_Forearm_Metal
      - Forearm_Forearm_Metal_to_End_Effector_MIP_Gripper_Interface
  - name: mip_junior_300/mip_gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - End_Effector_MIP_Gripper_Interface_to_End_Effector_MIP_Tooth_Left
      - End_Effector_MIP_Gripper_Interface_to_End_Effector_MIP_Tooth_Right
